title:               Happping Garden
include:             ['_pages']
exclude:
- _includes/notes_graph.json
- _notes/Dropbox/_OnlyMe
- _notes/Dropbox/.dropbox.cache
- _notes/Dropbox/.obsidian
- _notes/Dropbox/.trash
- _notes/Dropbox/.dropbox
- _notes/Dropbox/desktop.ini
- _notes/Dropbox/_Templates
- _notes/Dropbox/journals/.ignore


# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
